services:
  webserver:
    build: ${PWD}/webserver
    container_name: webserver
    volumes:
      - ${PWD}/app:/var/www/html
    ports:
      - 80:80
    links:
      - db
    deploy:
      resources:
          limits:
            cpus: "0.50"
            memory: 512M
          reservations:
            cpus: "0.25"
            memory: 128M
  db:
    image: mariadb:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rahasia
    restart: always
    volumes:
      - ${PWD}/database:/var/lib/mysql
    deploy:
      resources:
          limits:
            cpus: "1"
            memory: 512M
          reservations:
            cpus: "0.5"
            memory: 128M